### ISSUE TITLE
error in fog

### ISSUE THREAD

**Issue by elyast** [chef-boneyard/knife-eucalyptus#5]
I am getting constantly the same result: exception in fog, is there sth I am doing wrong?

.rvm/gems/ruby-1.9.2-p290/gems/fog-1.4.0/lib/fog/core/attributes.rb:141:in `merge_attributes': undefined method`each' for nil:NilClass (NoMethodError)
    from /Users/lukaszjastrzebski/.rvm/gems/ruby-1.9.2-p290/gems/fog-1.4.0/lib/fog/aws/models/compute/server.rb:183:in `save'
    from /Users/lukaszjastrzebski/.rvm/gems/ruby-1.9.2-p290/gems/fog-1.4.0/lib/fog/core/collection.rb:50:in`create'
    from /Users/lukaszjastrzebski/.rvm/gems/ruby-1.9.2-p290/gems/knife-eucalyptus-0.5.6/lib/chef/knife/euca_server_create.rb:162:in `run'
    from /Users/lukaszjastrzebski/.rvm/gems/ruby-1.9.2-p290/gems/chef-10.12.0/lib/chef/knife.rb:402:in`run_with_pretty_exceptions'
    from /Users/lukaszjastrzebski/.rvm/gems/ruby-1.9.2-p290/gems/chef-10.12.0/lib/chef/knife.rb:168:in `run'
    from /Users/lukaszjastrzebski/.rvm/gems/ruby-1.9.2-p290/gems/chef-10.12.0/lib/chef/application/knife.rb:123:in`run'
    from /Users/lukaszjastrzebski/.rvm/gems/ruby-1.9.2-p290/gems/chef-10.12.0/bin/knife:25:in `<top (required)>'
    from /Users/lukaszjastrzebski/.rvm/gems/ruby-1.9.2-p290/bin/knife:23:in`load'
    from /Users/lukaszjastrzebski/.rvm/gems/ruby-1.9.2-p290/bin/knife:23:in `<main>'

**Comment by llambeau** [comment]
I'm having the exact same issue... Did you find a solution @elyast?

**Comment by elyast** [comment]
Hi @llambeau not really, I havent really worked on this, so for my purposes I just wrap euca tools with thor.

**Comment by sethvargo** [comment]
Hey @elyast and @llambeau. Unfortunately we do not use github issues to track issues on the knife-plugins (hence why it's gone unnoticed). Could you please create a ticket in JIRA at https://tickets.opscode.com detailed this issue and the steps to reproduce? The Project is "Knife Plugins" and the Component is "knife-eucalyptus". Sorry about that :smile:
